.PHONY: clean All

All:
	@echo "----------Building project:[ GLEngine - Release ]----------"
	@cd "glEngine" && "$(MAKE)" -f  "GLEngine.mk"
clean:
	@echo "----------Cleaning project:[ GLEngine - Release ]----------"
	@cd "glEngine" && "$(MAKE)" -f  "GLEngine.mk" clean
